### ISSUE TITLE
Disable packages for this project

### ISSUE THREAD

**Issue by remcohaszing** [remarkjs/vscode-remark#102]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

This package is not an npm package, but it has been published as such. https://github.com/remarkjs/vscode-remark/packages/674442

In fact, it’s [the only package published](https://github.com/orgs/remarkjs/packages) to the @remarkjs organization.

### Solution

Unpublish the package and disable packages for this project.

### Alternatives

N/A

**Comment by wooorm** [comment]
sure

**Comment by wooorm** [comment]
Deleted it. The PR where it came from was https://github.com/remarkjs/vscode-remark/pull/70.

**Comment by remcohaszing** [comment]
The package has been removed, but could you also disable packages for the repo? IMO it always looks silly when GitHub shows the packages section when there are no packages. (Please fix this, GitHub :see_no_evil:)

**Comment by wooorm** [comment]
Is there an option for that?

**Comment by remcohaszing** [comment]
There’s a checkbox for it in the same dialog where you change the GitHub project description.

**Comment by wooorm** [comment]
Ohh you mean that one, yeah sure!
I thought you meant the “Packages” tab next to repositories, discussions, teams, etc: https://github.com/remarkjs

**Comment by remcohaszing** [comment]
I also wish GitHub would remove that! But nothing we can do about it.
