### ISSUE TITLE
Vfile API incomplete

### ISSUE THREAD

**Issue by cm226** [remarkjs/vscode-remark#107]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

v1.2.1

### Steps to reproduce

Use the remark-code-import plugin

### Expected behavior

remark-code-import runs and imports code into formatted document

### Actual behavior

When using the plugin 
"TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined"
is printed on the output console. 

The problem looks to be that the vFile API is only partially implemented on in the object passed to the transformer. remark-code-import uses https://github.com/vfile/vfile#filedirname to get a relative path to the files its importing from. 

When I checked the keys on the object passed as the vFile when running in this plugin i saw that only a handful of the keys were present. Would it possible to add the full vFile API to the object passed to the transformer? 

### Runtime

Electron

### Package manager

npm 8

### OS

Windows

**Comment by wooorm** [comment]
Inspecting fields on a file does not present them, because they are getters and setters.
What you see (or rather, don’t) hence is not a problem.

There were a lot of issues with this project. This project has been rewritten, but that has not been released yet. There are still a couple of small things missing.

The rewrite, and the next release will almost certainly fix your problem.

**Comment by cm226** [comment]
Thanks for getting back, whatever the reason accessing dirname property returns undefined in the object passed as the VFile in the currently version of the plugin, so if there is a getter defined its returning undefined. 

Good to know that you guys are re-writing, Ill close this issue given that and try again when you guys release the re-write thanks.

**Comment by wooorm** [comment]
> if there is a getter defined its returning undefined.

Yes, the errors means that the file does not have a path at all. I believe we’ve fixed that here
