### ISSUE TITLE
Remark will replace the contents of a markdown file with undefined if remark is not installed

### ISSUE THREAD

**Issue by trickypr** [remarkjs/vscode-remark#113]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

v2.0.0

### Steps to reproduce

1. Install the remark vscode extension
2. Open a folder that does not contain a remark installation
3. Format a markdown file
4. Experience the file being replaced with `undefined`

Runtime information:
 - Node `v18.6.0`
 - Build tool & package manager: `python-poetry` (I am trying to format files in a python project)

### Expected behavior

There should be an error telling you to install remark, but the file should be left unchanged.

### Actual behavior

There is an error telling you to install remark, but it also replaces the content of your file with `undefined`

### Runtime

Other (please specify in steps to reproduce)

### Package manager

Other (please specify in steps to reproduce)

### OS

macOS

### Build and bundle tools

Other (please specify in steps to reproduce)

**Comment by wooorm** [comment]
> `but it also replaces the content of your file with undefined`

That is a bug indeed.
However:

> `Uninstall any copies of the remark package`

You shouldn’t do that though.

My guess is that the processor is cached (the module was loaded in the past so it’s still in the module cache). I can’t imagine why it would start returning empty files though?

> It appears that you must install it locally for it to work, which seems annoying, especially for those who use format-on-save.

This is intentional for this project ([see readme](https://github.com/remarkjs/vscode-remark#when-should-i-use-this)).
It is intended that you use this in combination with a) configuration specific to the project, b) versioned dependencies, optionally/typically c) with `remark-cli` so that you can ensure in a CI/makefile/npm scripts/etc that people who don’t have VS Code, also format the same way you do with VS Code.

**Comment by trickypr** [comment]
> You shouldn’t do that though.
> 
> My guess is that the processor is cached (the module was loaded in the past so it’s still in the module cache).

I should be more clear that this happens before first install. In my case, Codacy was complaining that my markdown formatting was wrong and I got the vscode extension as a quick fix, without installing the lsp. I don't think that I have installed remark or the extension before, so I don't think it would be caching.

I have updated the reproduction steps to be more clear.

> I can’t imagine why it would start returning empty files though?

By `undefined`, I don't mean empty files. I mean replacing the contents of the file with `undefined`.

![Kapture 2022-07-26 at 21 55 46](https://user-images.githubusercontent.com/23250792/181000280-9777830c-b342-4829-b18d-c7f9ed288b9f.gif)

> This is intentional for this project ([see readme](https://github.com/remarkjs/vscode-remark#when-should-i-use-this)).

Sorry, I skimmed the project name and ignored the readme. That is entirely my fault.

**Comment by wooorm** [comment]
> I have updated the reproduction steps to be more clear.

Ahhh okay, that makes more sense, thanks.

---

/cc @remcohaszing

**Comment by remcohaszing** [comment]
I noticed a situation where the file contents are replaced with `undefined` myself. This should never happen, it’s worse than errors. I will investigate.

**Comment by remcohaszing** [comment]
Theis was fixed in https://github.com/unifiedjs/unified-language-server/pull/51 and released in version [2.1.0](https://github.com/remarkjs/vscode-remark/releases/tag/2.1.0).
