### ISSUE TITLE
`private: true` in `package.json`

### ISSUE THREAD

**Issue by wooorm** [remarkjs/vscode-remark#117]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

The package can accidentally be published to npm.

### Solution

Can we add `private: true` to `package.json`? Or would that prevent publishing to the extension marketplace?

### Alternatives

-

**Comment by JounQin** [comment]
It is indeed enabled at [`vscode-mdx`](https://github.com/mdx-js/vscode-mdx/blob/master/package.json#L48).
