### ISSUE TITLE
Use no-code VSCode integration

### ISSUE THREAD

**Issue by remcohaszing** [remarkjs/vscode-remark#121]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

Currently we need a bunch of boilerplate code to create a client for integrating `remark-language-server` into this extension. This adds ~350kB of minified JavaScript.

### Solution

I created feature request https://github.com/microsoft/vscode/issues/158076 upstream. If it gets accepted (needs 20 :+1: votes) and implemented, we can remove the client code entirely.

### Alternatives

If the upstream doesn’t get accepted, we should just close this issue.

**Comment by wooorm** [comment]
@remarkjs/contributors The call to action here is: Please upvote this issue https://github.com/microsoft/vscode/issues/158076 (assuming you think it is a good idea 😉). Thanks!

**Comment by wooorm** [comment]
@remarkjs/contributors Friendly ping 🛎. Only 4 :+1: are missing!

**Comment by JounQin** [comment]
I just asked my colleagues for help.

**Comment by wooorm** [comment]
Should we keep this open? It’s been more than a year. Might be never.

**Comment by remcohaszing** [comment]
My plan was basically:

- Wait for `remark-lint` releases
- Release `remark-language-server`
- Release `vscode-remark`
- Close this issue as _We’ll see whenever this gets implemented_.

So yeah, I’ll close it now.
