### ISSUE TITLE
Use globally installed `remark` package when no local dependencies

### ISSUE THREAD

**Issue by Jisu-Woniu** [remarkjs/vscode-remark#124]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

Not all of my repositories are developed with Node.js, and I don't like to have `package.json` and `node-modules` wherever I have markdown files.

### Solution

I would suggest using globally installed `remark` package when no local dependencies is in local directory.

It would be even better if you install it in the plugin's data folder.

### Alternatives

I have no more ideas.

**Comment by wooorm** [comment]
You really should version the tools you use. Stuff is going to break otherwise.

**Comment by Jisu-Woniu** [comment]
But I still don't see any point to put a package.json in my C++ or Java projects just because they have a `README.md`.

I can just use a global version management for all these dependencies. Maybe you should allow us to use it as a fallback.

**Comment by remcohaszing** [comment]
I think this is what you’re looking for: https://github.com/unifiedjs/unified-language-server/issues/30

It has been delayed for a bit, but I can have another look at it.

For now I suggest to just disable the extension in workspaces where you don’t use remark.

**Comment by Murderlon** [comment]
> But I still don't see any point to put a package.json in my C# or Java projects just because they have a `README.md`.

Some extra context on why a global remark wouldn't do much (or anything):

https://github.com/orgs/remarkjs/discussions/960#discussioncomment-2270454

**Comment by wooorm** [comment]
> any point to put a package.json in my C# or Java projects just because they have a README.md

- If you don’t specify versions, things will change, because your CI has different versions and configuration
- If you don’t share configuration, other contributors will users different styles, meaning they can’t contribute to your markdown in the way you want

**Comment by Jisu-Woniu** [comment]
> > any point to put a package.json in my C# or Java projects just because they have a README.md
> 
> - If you don’t specify versions, things will change, because your CI has different versions and configuration
> - If you don’t share configuration, other contributors will users different styles, meaning they can’t contribute to your markdown in the way you want

It is not a "what I should do" problem, but a "what I need" one. I don't have anyone to work with in my programming homework. Even if you think it's not the best practice, you should allow me to do so with a checkbox in the extension setting.

**Comment by wooorm** [comment]
> you should at least allow me

This is not how open source works. Random people from the internet don’t get to dictate what someone else works on and maintains. This is what you get: https://github.com/remarkjs/vscode-remark/blob/main/license

**Comment by Jisu-Woniu** [comment]
If I really need to use a fixed markdown style in my workspace, what I need is a `remarkrc`, not a remark version note in `package.json`.

Just like when I want a consistent C++ code style, I would use a `.clang-format` configuration file, not a customized version of the clang-format binary. A binary version doesn't ensure anything.

**Comment by wooorm** [comment]
> not a remark version note in package.json

Versions include major changes. Major changes mean that what you configure currently does not work the same as on another point in time.

> when I want a consistent C++ code style

This project works different from `.clang-format`.

**Comment by remcohaszing** [comment]
If you wish to format documents without any configuration, I suggest to use [Prettier](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) instead.

---

The repository description is outdated. That might give a false sense of what the extension does. I think we should match it with the description in `package.json`.

**Comment by Jisu-Woniu** [comment]
> I suggest to use [Prettier](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) instead.

Thank you, it helps.

**Comment by wooorm** [comment]
So it sounds like you don’t want to use remark/unified and benefit from its ecosystem, you’re instead looking for a markdown formatter with low configuration, such as prettier. That’s fine, and it isn’t the space that remark tries to occupy. So I think the actual question is now answered.

@remcohaszing fixed!
