### ISSUE TITLE
Feature Request: Fix Errors On Save

### ISSUE THREAD

**Issue by anthony0030** [remarkjs/vscode-remark#17]
Is there a way to add a ```format on save``` function?

**Comment by ouuan** [comment]
Isn't it `editor.formatOnSave`? Do you want a specific setting for this formatter?

**Comment by anthony0030** [comment]
I have that setting on. The only way I can get it to format is with the command palet in vscode.

**Comment by ouuan** [comment]
> I have that setting on. The only way I can get it to format is with the command palet in vscode.

You may need this in your settings.json:

```
    "[markdown]": {
        "editor.defaultFormatter": "mrmlnc.vscode-remark"
    },
```

**Comment by anthony0030** [comment]
It shows the errors when I save but won't autocorrect on save. I can run the command in VScode pallet and it works.

**Comment by ouuan** [comment]
> It shows the errors when I save but won't autocorrect on save. I can run the command in VScode pallet and it works.

That's the problem: it shows the error instead of correcting them. So I think what we need is not a setting to format on save, but fixing this problem, which not only enables format on save, but also enables other formatting features of VS Code, like the shortcut, format on paste, etc.

**Comment by anthony0030** [comment]
How would I do this?

**Comment by ouuan** [comment]
> How would I do this?

I'm also a normal user. I'm just suggesting you modify your feature request.
