### ISSUE TITLE
Set up Dependabot

### ISSUE THREAD

**Issue by asbjornu** [remarkjs/vscode-remark#27]
### Subject of the feature

It would be great to have [Dependabot](https://dependabot.com/) set up to ensure that all dependencies are up to date.

**Comment by asbjornu** [comment]
Think you can look into this, @ChristianMurphy? 🙏

**Comment by wooorm** [comment]
@asbjornu Can you clarify why you want to add dependabot?

**Comment by asbjornu** [comment]
@woorm:

> to ensure that all dependencies are up to date

**Comment by ChristianMurphy** [comment]
There are some options here, dependabot is one.
Another, used by [several](https://github.com/mdx-js/mdx) [unified](https://github.com/remarkjs/grunt-remark) [projects](https://github.com/mdx-js/eslint-mdx) already, is [renovate bot](https://github.com/renovatebot/renovate) ([docs](https://docs.renovatebot.com/)).
Renovate offers more configuration than [dependabot](https://dependabot.com/) or [greenkeeper](https://greenkeeper.io/), which can be useful for PR noise reduction.

**Comment by asbjornu** [comment]
I've never used Renovate before and it looks more involved to get up and running than Dependabot, so I would appreciate if someone who has experience with it could set it up. 🙏  As long as dependencies are kept up to date by automatic pull requests, I'm not fuzzy where the pull requests come from.
