### ISSUE TITLE
Create Remark organization on Azure DevOps

### ISSUE THREAD

**Issue by asbjornu** [remarkjs/vscode-remark#28]
### Subject of the feature

As suggested in https://github.com/remarkjs/remark/issues/508#issuecomment-660086559 we need a `remark` organization in Azure DevOps under which we can publish new versions of this extension. [Here's a recipe for the entire publishing process](https://code.visualstudio.com/api/working-with-extensions/publishing-extension).

As soon as the personal access token and everything else is set up as secrets in this repository, I can get to work on automating the publishing process.

**Comment by asbjornu** [comment]
@ChristianMurphy, can you please assist with this? 🙏

**Comment by wooorm** [comment]
This project seems to average about 1 release per year (5 releases since 2016). I’m generally a fan of cutting releases by hand. What benefits do you see by automating releases?

**Comment by asbjornu** [comment]
Regardless of the automation, we need an organization, which by the lack of access to this repository and the remark organization I can't.

Regarding the automation, I can't think of a good reason to not publish on every `git tag` preformed in the repository. How often that has happened in the past is not indicative of how often it's going to happen in the future, with a new maintainer. Also, if the release process happens seldom, it's even more important to automate it, as there's little I hate more than having to re-read documentation on how to perform a release on a platform because it's so long since I last did it I have forgotten how to do it. Baking it in to a simple GitHub workflow is the simplest way to ensure that releases stay consistent over time, imho.

**Comment by ChristianMurphy** [comment]
/cc @jounqin from https://github.com/mdx-js/vscode-mdx
I notice the mdx vscode plugin is running off the JounQin namespace https://marketplace.visualstudio.com/items?itemName=JounQin.vscode-mdx
Is it easier to run off a personal namespace, or would there be value in creating an organization?

**Comment by wooorm** [comment]
@ChristianMurphy See also the previous discussion about downsides of personal namespaces: https://github.com/remarkjs/remark/issues/508#issuecomment-653866681

**Comment by asbjornu** [comment]
[Creating an organization](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/create-organization?view=azure-devops) is simple enough and makes the published extensions independent of one single person, reducing the [bus factor](https://en.wikipedia.org/wiki/Bus_factor). If you have several projects underneath the Remark umbrella published on the Visual Studio Marketplace, I think that argues even more strongly for creating a Remark organization on there.

**Comment by asbjornu** [comment]
@ChristianMurphy, @wooorm, is it anything I can do to assist in the creation of a RemarkJS organization?

**Comment by asbjornu** [comment]
@ChristianMurphy @wooorm Ping?

**Comment by JounQin** [comment]
+1 for official organization personally

**Comment by wooorm** [comment]
Sorry, @asbjornu, thanks for the ping!

@asbjornu @JounQin As we’re talking `vscode-remark` and `vscode-mdx`, which fall under different organisations, does **unified** (or **unifiedjs**) or so sound good?

**Comment by JounQin** [comment]
@wooorm I'm in favor of `unifiedjs` which is also the GitHub organization name.

**Comment by asbjornu** [comment]
Sounds good to me!

**Comment by wooorm** [comment]
cool cool! @asbjornu, I believe you volunteered to set it up, right? I’d appreciate that. Otherwise I can try my hands at it!

**Comment by asbjornu** [comment]
Sure, I've now created the [Unified.js publisher on the VS Marketplace](https://marketplace.visualstudio.com/publishers/unifiedjs). Let me know your Microsoft Account e-mails so I can add you to it. I'll close this issue and will create a new one for publishing to the VS Marketplace.

**Comment by wooorm** [comment]
Thanks @asbjornu. I’m using my gmail listed here: https://github.com/wooorm.
Also, @ChristianMurphy, @JounQin?

**Comment by ChristianMurphy** [comment]
My email is listed here: https://github.com/ChristianMurphy

**Comment by asbjornu** [comment]
Sorry, neither of those addresses seem to work. Are they registered Microsoft Accounts?

<img width="192" alt="Invalid domain" src="https://user-images.githubusercontent.com/12283/111332689-4a8bc600-8672-11eb-82ff-8eae86e65c4e.png">

<img width="238" alt="Invalid domain" src="https://user-images.githubusercontent.com/12283/111332654-43fd4e80-8672-11eb-93fd-343b84434629.png">

**Comment by JounQin** [comment]
@asbjornu https://github.com/JounQin

**Comment by asbjornu** [comment]
Seems like [there's a bug](https://stackoverflow.com/questions/56032912/vs-marketplace-add-member-displayes-invalid-domain-error). I'll see whether I can circumvent it somehow.

**Comment by JounQin** [comment]
> @asbjornu https://github.com/JounQin

Maybe you can try liujiaren1992#outlook.com

**Comment by asbjornu** [comment]
> Maybe you can try liujiaren1992#outlook.com

Sorry, that didn't work either.

<img width="199" alt="Invalid doman" src="https://user-images.githubusercontent.com/12283/111334681-10232880-8674-11eb-8e7f-d10ead807c36.png">

This is a bug and the only way around seems to be to send Microsoft the ID of your Microsoft Accounts. To retrieve your Microsoft Account ID please do the following:

1. Login to the [Marketplace](https://marketplace.visualstudio.com) with the email address that has to be added to the publisher.
2. After getting logged in, from the same browser window, open [this API URL](https://marketplace.visualstudio.com/_apis/connectiondata).
3. In the JSON, please find the value of `authenticatedUser.id` and paste it here.

**Comment by wooorm** [comment]
LOL

**Comment by JounQin** [comment]
@asbjornu Please help to delete the image at https://github.com/remarkjs/vscode-remark/issues/28#issuecomment-800361034 like https://github.com/remarkjs/vscode-remark/issues/28#issuecomment-800349709

**Comment by ChristianMurphy** [comment]
`f39e7fd2-43fe-45dc-8eb7-9eed90da28db`

**Comment by JounQin** [comment]
@ChristianMurphy The email text is not been removed at https://github.com/remarkjs/vscode-remark/issues/28#issuecomment-800361034 😂
