### ISSUE TITLE
Set up Codecov

### ISSUE THREAD

**Issue by asbjornu** [remarkjs/vscode-remark#29]
### Subject of the feature

Create a token for [Codecov](https://codecov.io/) so we can have code coverage reporting in the project and add it as a GitHub secret so code coverage reports can be submitted.

### Problem

We currently have no overview of the code coverage of the tests in the project.

### Expected behavior

I expect to know approximately how well tested a codebase is. I don't need a precise percentage and 100% should be actively discouraged to avoid tight coupling between tests and code, making refactoring difficult, but somewhere between 60% and 80% is usually healthy.

### Alternatives

There are many code coverage platforms, but I especially like Codecov since it has good integration with GitHub with its code review assertions and report comments and it can be configured to fail builds if coverage drops by merging a PR, for instance.

**Comment by ChristianMurphy** [comment]
There are a few coverage platforms, codecov is already used on [unified](https://codecov.io/github/unifiedjs/unified). It could be used here as well.
Write access to the repo is all that's needed, it can be setup with any of the major CI's, here are the instructions for use with GitHub actions https://github.com/marketplace/actions/codecov

**Comment by asbjornu** [comment]
Ah, the part about only needing tokens for private repos was new to me. I'll go right ahead and implement then. Thanks, @ChristianMurphy.

**Comment by wooorm** [comment]
@asbjornu Can you clarify your experience regarding the notion that 100% is bad? I strongly feel that classifying 100% as unhealthy is woefully incorrect.

**Comment by asbjornu** [comment]
I'm not categorically saying that 100% code coverage is always bad, but I have seen quite a bit of projects where the unit tests has had to know so much about the internal workings of the application in order to reach ~100% that refactoring the codebase was pretty much impossible.

If the code base that is being tested exports a public interface, **that** should have 100% test coverage. But the private parts should be mostly left alone, minus a few core features that are essential to the workings of the application and also near to impossible to debug "from the outside".

But all code bases are different, so different metrics apply everywhere.

**Comment by ChristianMurphy** [comment]
@asbjornu have you had a chance to take a look at setting this up?

**Comment by asbjornu** [comment]
@ChristianMurphy, I did some work on it back in September, but looking at the commits now I remember vaguely running into some trouble hooking Codecov up in the test runner. I can't remember the specifics at the moment.
