### ISSUE TITLE
Rename master to main

### ISSUE THREAD

**Issue by asbjornu** [remarkjs/vscode-remark#39]
### Subject of the feature

As seems to become the standard everywhere, it's good to follow suit and rename `master` to `main`.

### Problem

[The rationale to rename `master` to `main` is explained well here](https://github.com/github/renaming).

**Comment by wooorm** [comment]
yep, we’re all for it (most of our repos are changed already).

Want me to do it here? GHs new features should update everything nicely. Or is there something you want to merge/do first?

**Comment by asbjornu** [comment]
> Want me to do it here? 

Yes please! 😃

**Comment by wooorm** [comment]
Done!
