### ISSUE TITLE
Bundle the extension

### ISSUE THREAD

**Issue by asbjornu** [remarkjs/vscode-remark#41]
### Subject of the feature

According to Microsoft's best practices, [VS Code extensions should be bundled](https://code.visualstudio.com/api/working-with-extensions/bundling-extension). 

### Problem

When executing `vsce package` now, the following is written to the console:

>This extension consists of 359 files, out of which 193 are JavaScript files. For performance reasons, you should bundle your extension: https://aka.ms/vscode-bundle-extension . You should also exclude unnecessary files by adding them to your .vscodeignore: https://aka.ms/vscode-vscodeignore

The large amount of JavaScript files being packaged is due to the entire `node_modules` directory being added to the `.vsix` archive. Bundling will pull every dependency into one large `extension.js` file, making it possible to ignore the `node_modules` directory and pretty much everything else, greatly reducing the size of the package.

### Alternatives

Webpack is suggested, but I think there are alternative bundlers that may be used. Bundling is unchartered territory for me, so I have no preference.

**Comment by wooorm** [comment]
esbuild can do this: make a bundle for node. And it’s really fast. Otherwise, https://github.com/vercel/ncc is a webpack wrapper I believe?

**Comment by asbjornu** [comment]
Sounds good, @wooorm! I'm not familiar with any bundler at all 😅.
