### ISSUE TITLE
Unpublish mrmlnc.vscode-remark

### ISSUE THREAD

**Issue by asbjornu** [remarkjs/vscode-remark#44]
### Subject of the feature

Now that the extension is published under the name [unifiedjs.vscode-remark](https://marketplace.visualstudio.com/items?itemName=unifiedjs.vscode-remark) we should [unpublish](https://docs.microsoft.com/en-us/azure/devops/extend/publish/overview?view=azure-devops#unpublish-an-extension) [mrmlnc.vscode-remark](https://marketplace.visualstudio.com/items?itemName=mrmlnc.vscode-remark) to avoid confusion. Can you please do this @mrmlnc?

### Problem

With two extensions bearing the same name and icon on the VSCE Marketplace, it's going to be confusion around which is the official one.

**Comment by wooorm** [comment]
Icon should change, it doesn’t match the rest of the unified “branding”. What should we go with?

And, assuming Denis is getting a lot of notifications from this repo, might be good to ping them again in a couple days.

**Comment by asbjornu** [comment]
> Icon should change, it doesn’t match the rest of the unified “branding”. What should we go with?

I give a new icon 👍🏼. Do you have ideas for how it should look or should I throw up a sketch?

> And, assuming Denis is getting a lot of notifications from this repo, might be good to ping them again in a couple days.

Indeed.

**Comment by wooorm** [comment]
@asbjornu any reason to not use the [remark logo](https://avatars.githubusercontent.com/u/16309564?s=1200&u=5d88e91c5c201e6144e4564c4f4aa865dc46130c&v=4) (or [banner](https://github.com/remarkjs/remark/blob/main/logo.svg))?

**Comment by asbjornu** [comment]
No reason, that should be fine. We might want to have the words "VS Code" in there, perhaps? Also, why is the font different in the logo and banner and which fonts are used?

**Comment by wooorm** [comment]
I don’t see those words appearing in any of the other logos (e.g., https://marketplace.visualstudio.com/search?target=VSCode&category=Other&sortBy=Installs). And they might even not allow it (similar to how you can’t use GH logos or name either).
Reason for different font weight is that logos are often displayed tiny. And monospace there might take more space than needed. But that might be worth revisiting.

**Comment by asbjornu** [comment]
Good points wrt. the use of "VS Code". Personally, I like the monospace used in the banner best. Which font is it?

**Comment by wooorm** [comment]
Friendly ping @mrmlnc!

**Comment by remcohaszing** [comment]
VS Code now supports deprecation. Extension deprecations can be requested via https://github.com/microsoft/vscode-discussions/discussions/1.

**Comment by wooorm** [comment]
Let’s first get this release out proper, then ping mrminc to do this!

**Comment by remcohaszing** [comment]
> Let’s first get this release out proper, then ping mrminc to do this!

I agree. That’s a much nicer way to do it.

**Comment by wooorm** [comment]
Hi @mrmlnc! Hope you’re good :) Can you request deprecation of your package, in favor of our package, here: https://github.com/microsoft/vscode-discussions/discussions/1?

**Comment by remcohaszing** [comment]
I have requested a deprecation: https://github.com/microsoft/vscode-discussions/discussions/1#discussioncomment-4861479

**Comment by remcohaszing** [comment]
The old extension has been deprecated.
