### ISSUE TITLE
Automatically merge dependency updates

### ISSUE THREAD

**Issue by asbjornu** [remarkjs/vscode-remark#46]
### Subject of the feature

With the tests we now have I feel fairly confident about having dependency updates by Renovate automatically merged if the tests are successful. I don't know Renovate, but if it doesn't have this feature, we can use [Mergify](https://mergify.io/) to both review and merge pull requests from Renovate.

### Problem

It requires quite a bit of manual labour to go through pull requests from Renovate, review them and merge them, then wait for the next PR to be rebased and then review and merge that as well, and so on. It would be great if this could be automated.

### Expected behavior

I expect dependency updates to be automatically merged if the tests are successful.

**Comment by wooorm** [comment]
There are a lot of renovate PRs out currently, but I don‘t think that’s the normal state of things.
What you describe in problem, I don’t think should be automated: dependencies often conflict. Without a rebase in between, stuff will go unnoticed.
I also believe dependency updates should be either done manually or manually reviewed. You can’t trust npm.

Doesn’t GH make automerging pretty swift?: https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/automatically-merging-a-pull-request

**Comment by asbjornu** [comment]
> There are a lot of renovate PRs out currently, but I don‘t think that’s the normal state of things.

That's not my experience with most JavaScript- and Typescript-based projects. Updates happen frequently enough and the work involved is tedious and boring enough that it should be automated, imho.

> What you describe in problem, I don’t think should be automated: dependencies often conflict. Without a rebase in between, stuff will go unnoticed.

Rebasing is already taken care of by Renovate, so I don't see the problem? Merging of stale PRs is impossible by the branch protection.

> I also believe dependency updates should be either done manually or manually reviewed. You can’t trust npm.

I see the trust issue. That's a valid argument. However, I must admit I don't do an extensive review of whether an update of a dependency may have snuck in rogue code or not. At least not in this repository. If that's the kind of review you think we need here, I'm sorry to say I won't be doing it.

> Doesn’t GH make automerging pretty swift?: https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/automatically-merging-a-pull-request

That still requires manually clicking 4 times for every open pull request. The ideal would be 0 clicks, imho.

**Comment by wooorm** [comment]
> That's not my experience with most JavaScript- and Typescript-based projects. Updates happen frequently enough and the work involved is tedious and boring enough that it should be automated, imho.

This project has 3 dependencies, which are all stable: https://github.com/remarkjs/vscode-remark/blob/7ea2957e1c4368e78bcf4749154db60dba73672b/package.json#L241-L243. That at most 3 PRs a year.
For the dev-dependencies, I think PRs for those are churn. I bet renovate can be configured to batch those up with big delays.

> Rebasing is already taken care of by Renovate, so I don't see the problem? Merging of stale PRs is impossible by the branch protection.

This was in reply to your Problem statement, where you explained that it’s cumbersome to wait for that rebase.

> I see the trust issue. That's a valid argument. However, I must admit I don't do an extensive review of whether an update of a dependency may have snuck in rogue code or not. At least not in this repository. If that's the kind of review you think we need here, I'm sorry to say I won't be doing it.

I’m not saying that, relax. We’re talking about auto-merging without a human in sight here. I’m saying a glance over the PR, 3 times a year, is not too much.

> That still requires manually clicking 4 times for every open pull request. The ideal would be 0 clicks, imho.

The four clicks are irrelevant in time. The time is in reviewing a PR. You’re proposing to not review PRs. I’m saying that we should.

**Comment by asbjornu** [comment]
Ok, then I hope I'll receive help in review going forward. The PRs from Renovate I just went through were many months old.
