### ISSUE TITLE
Verify Unified.js as a publisher

### ISSUE THREAD

**Issue by remcohaszing** [remarkjs/vscode-remark#67]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

Visual Studio Code extensions can publishers can become a a varified published to verfying the ownership of the registered domain name. This requires access to both the Visual Studio Marketplace management page and the DNS settings for the domain (`unifiedjs.com`).

Being a verified publisher signals users the extension is officially published by Unified.

Instructions can be found [here](https://code.visualstudio.com/api/working-with-extensions/publishing-extension#verify-a-publisher)

### Solution

Verify Unified.js as a publisher.

### Alternatives

Don’t verify Unified.js as a publisher :shrug:

**Comment by wooorm** [comment]
Should probably do the same with github, right:
https://docs.github.com/en/organizations/managing-organization-settings/verifying-or-approving-a-domain-for-your-organization

**Comment by wooorm** [comment]
Well, I did manage to verify the orgs on GH.
The VSCode marketplace is now awaiting manual reviewing. So I guess that’s somewhere early next year? 🤷‍♂️

**Comment by wooorm** [comment]
I’m going to close this because there’s nothing else to do here, and I’m assuming it’ll just “magically” start working when they get to it 🤷‍♂️

**Comment by remcohaszing** [comment]
![image](https://user-images.githubusercontent.com/779047/147921220-d8883151-00aa-4541-a921-62d6a575199a.png)

I see a nice checkmark :smile:

**Comment by wooorm** [comment]
sweeeet!
